image: alanz/hare-ci
cache:
  paths:
    - .stack
    - .cabal
    - .cache/cabal-helper

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

job-ghc-7.10.3:
  script:
      - stack --stack-yaml=stack-7.10.3.yaml setup
      - stack --stack-yaml=stack-7.10.3.yaml test

job-ghc-8.0.1:
  script:
      - stack --stack-yaml=stack-8.0.1.yaml setup
      - stack --stack-yaml=stack-8.0.1.yaml test

job-ghc-8.0.2:
  script:
      - stack --stack-yaml=stack-8.0.2.yaml setup
      - stack --stack-yaml=stack-8.0.2.yaml test

job-ghc-8.2.1:
  script:
      - stack --stack-yaml=stack-8.2.1.yaml setup
      - stack --stack-yaml=stack-8.2.1.yaml test

job-ghc-8.2.2:
  script:
      - stack --stack-yaml=stack-8.2.2.yaml setup
      - stack --stack-yaml=stack-8.2.2.yaml test

job-ghc-8.4.1:
  script:
      # - export export cabal_helper_libexecdir=~/.local/bin
      - export export cabal_helper_libexecdir=.stack-work/install/x86_64-linux-nopie/nightly-2018-04-15/8.4.1/bin
      - stack --stack-yaml=stack-8.4.1.yaml setup
      - stack --stack-yaml=stack-8.4.1.yaml test

